#spring:
#  cloud:
#    gateway:
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "http://localhost:8761"
#            allowedHeaders:
#              - content-type
#            allowedMethods:
#              - GET
#              - POST
#              - PUT
#              - DELETE
#  cloud:
#    gateway:
#      routes:
#        - id: oauth-server
#          uri: http://127.0.0.1:9000
#          predicates:
#            - Path=/oauth2/**
#            - Path=/login
#        - id: client-server
#          uri: http://127.0.0.1:8088
#          predicates:
#            - Path=/api/**
#        - id: resource-server
#          uri: http://localhost:8090
#          predicates:
##            - Path=/api/users
##
##          filters:
##            - AddRequestHeader= Authorization
#            - AuthenticationFilter
#            - RemoveRequestHeader = Cookie
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

